# Generated by Django 4.1.1 on 2022-09-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='sharable_to',
            field=models.IntegerField(default=1),
        ),
    ]
